"use strict";
let Question23 = () => {
    let name = "Umair";
    console.log("name == malik; I predect true");
    console.log(name == "malik");
    console.log("name == malik; I predect false");
    console.log(name == "malik");
    let age = 25;
    console.log("age == 25; I predect true");
    console.log(age == 25);
    console.log("age == 30; I predect false");
    console.log(age == 30);
    let isStudent = true;
    console.log("isStudent == true; I predect true");
    console.log(isStudent == true);
    console.log("isStudent == false; I predect false");
    console.log(isStudent == true);
    let sport = "cricket";
    console.log("sport == cricket; I predect true");
    console.log(sport == "cricket");
    console.log("sport == football; I predect false");
    console.log(sport == "football");
    let noOneBatsman = "Babar Azam";
    console.log("noOneBatsman == Babar Azam; I predect false");
    console.log(noOneBatsman == "Babar Azam");
    console.log("noOneBatsman == Virat Kohli; I predect true");
    console.log(noOneBatsman == "Virat Kohli");
    let noOneBowler = "Shaheen Afridi";
    console.log("noOneBowler == Shaheen Afridi; I predect false");
    console.log(noOneBowler == "Shaheen Afridi");
    console.log("noOneBowler == Jasprit Bumrah; I predect true");
    console.log(noOneBowler == "Jasprit Bumrah");
};
Question23();
